version: '3'
services:
    app:
        build: .
        ports:
            - "8080:8080"
        environment:
            - DATASOURCES_DEFAULT_URL=jdbc:postgresql://db:5432/key_keeper
            - DATASOURCES_DEFAULT_USERNAME=postgres
            - DATASOURCES_DEFAULT_PASSWORD=postgres
        depends_on:
            - db
            - mongodb  # Dependência do MongoDB

    db:
        image: postgres:16
        environment:
            POSTGRES_DB: key_keeper
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5433:5432"
        networks:
            - mongo_network  # Conectar com a rede do MongoDB

    mongodb:
        image: mongo:6.0
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        networks:
            - mongo_network  # Conectar com a rede do PostgreSQL e da aplicação

volumes:
    mongodb_data:
        driver: local

networks:
    mongo_network:
        driver: bridge
