version: '3'
services:
    app:
        build: .
        ports:
            - "8080:8080"
        environment:
            - DATASOURCES_DEFAULT_URL=jdbc:postgresql://db:5432/key_keeper
            - DATASOURCES_DEFAULT_USERNAME=postgres
            - DATASOURCES_DEFAULT_PASSWORD=postgres
        depends_on:
            - db

    db:
        image: postgres:16
        environment:
            POSTGRES_DB: key_keeper
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5433:5432"
